### ISSUE TITLE
When I update my account, the account is canceled 

### ISSUE THREAD

**Issue by ahmadajmi** [Health-Care/BloodDonation#15]

**Comment by ibrahimali123** [comment]
@ahmadajmi  it works right, I try it several times.

**Comment by ibrahimali123** [comment]
make sure you click update not its below button "cancel account" :) :)

**Comment by ahmadajmi** [comment]
Thanks Ibrahim, It was an issue in my branch and fixed, just the button was not indentation properly in Haml.
